using System;
using System.Collections.Generic;
using Godot;

namespace GamejamV2.scripts;
public partial class Words : Node
{
    public static readonly Dictionary<String, Impact> words = new() {
        {"les armes", new Impact(-2, -5, 5)},
        {"l'argent", new Impact(5, 5, 5)},
        {"les taxes", new Impact(-5, 3, 5)},
        {"les familles", new Impact(3, 5, 0)},
        {"les enfants", new Impact(1, 5, 2)},
        {"les provisions", new Impact(-3, 0, 4)},
        {"l'injustice", new Impact(-4, -3, -3)},
        {"les territoires", new Impact(2, 1, 5)},
        {"les pommes", new Impact(4, 0, 0)},
        {"les femmes", new Impact(3, 2, 1)},
        {"les hommes", new Impact(0, 0, 5)},
        {"les pains", new Impact(4, 1, 2)},
        {"la terre", new Impact(4, 2, 0)},
        {"les scientifiques", new Impact(0, -5, -2)},
        {"la bourgeoisie", new Impact(-4, 2, -1) },
        {"la médecine", new Impact(4 ,-3 , 3)},
        {"le commerce", new Impact(3, -1, 0) },
        {"la bible", new Impact(-2, 5, 2) },
        {"la religion", new Impact(-2, 5, 2) },
        {"Léonardo DaVinci", new Impact(0, -4, 1) },
        {"les croisades", new Impact(-3, 4, 3) },
        {"la chasse", new Impact(3, 0, 1) },
        {"les prisoniers", new Impact(-3, -1, -3) },
        {"les cathédrales", new Impact(0, 3, 2) },
        {"la coupe Stanley", new Impact(5, 5, 5) },
        {"la littérature", new(2, -4, 0) },
        {"les voyages", new Impact(1, 0, 1) },
        {"la conquête", new Impact(0, 1, 3) },
        {"les auberges", new Impact(1, 0, 2) },
        {"l'éducation", new Impact(1, -3, 2) },
        {"les hopitaux", new Impact(3, 2, 1) },
        {"le mariage", new(2, 4, -3) },
        {"le divorce", new Impact(-2, -5, 0) },
        {"la paix", new Impact(3, 3, 3) },
        {"le malheur", new Impact(-4, -4, -4) },
        {"la dette publique", new Impact(-4, -2, -2) },
        {"les poubelles", new Impact(-3, -1, -1) },
        {"la démocratie", new Impact(4, -4, 0) },
        {"le travail", new Impact(-3, 2, 3) },
        {"la petite souris", new Impact(-2, -2, -2) },
        {"Les coupes de cheveux", new Impact(1, 0, 0) },
        {"l'hygiène", new Impact(1, 3, 2) },
        {"les cultes", new Impact(-1, -5, -2) },
        {"le troisième lien", new Impact(-3, 3, -3) },
        {"l'humanisme", new Impact(1, -3, -3)},
        {"l'imprimerie", new Impact(1, -2, 1) },
        {"l'Index", new Impact(-1, -5, -3) },
        {"les arts", new Impact(1, 3, 0) },
        {"la monarchie", new Impact(-4, 2, 3) },
        {"le nouveau monde", new Impact(-2, 4, 1) },
        {"la terre plate", new Impact(1, 4, 1) },
        {"l'héliocentrisme", new Impact(1, -4, 1) },
        {"Galilée", new Impact(1, -3, 2) },
        {"la liberté d'expression", new Impact(5, -3, -2) },
        {"le blé", new Impact(5, 2, 3) },
        {"la dîme", new Impact(-4, 4, 0) },
        {"la patrie", new Impact(1, 2, 5) },
        {"les bateaux", new Impact(0, 1, 5) },
        {"la censure", new Impact(-3, 4, 1)},
        {"la musique", new Impact(0, 4, 2)},
        {"l'agriculture", new Impact(4, 3, 1)},
        {"la guerre", new Impact(-4, -3, 3)},
        {"la tradition", new Impact(3, 3, 3)},
        {"la fierté", new Impact(1, -3, 3)},
        {"les haricots verts", new Impact(4, 1, 1)},
        {"le danger", new Impact(-2, -4, 4)},
        {"le crime", new Impact(-3, -2, -1)},
        {"les nouvelles idées", new Impact(0, -3, 1)},
        {"une belle récolte", new Impact(4, 1, 1)},
        {"les mémères", new Impact(2, 1, 2)},
        {"le forgeron du village", new Impact(2, 1, 1)},
        {"la Mona Lisa", new Impact(0, 2, 2)},
        {"le bon vin", new Impact(3, 1, 3)},
    };
}